export const dummyStocks = [
    {
        id: 1,
        StockName: 'A전자',
        itmsNm: '가전',
        type: 'stock',
        DailyPrice: 65000,
        clpr: 45000,
        fltRt: 0.05,
        Field: 5,
    },
    {
        id: 2,
        StockName: 'B자동차',
        itmsNm: '자동차',
        type: 'stock',
        DailyPrice: 85000,
        clpr: 78000,
        fltRt: 0.03,
        Field: 4,
    },
    {
        id: 3,
        StockName: 'C화학',
        itmsNm: '화학',
        type: 'stock',
        DailyPrice: 120000,
        clpr: 115000,
        fltRt: 0.04,
        Field: 3,
    },
    {
        id: 4,
        StockName: 'D금속',
        itmsNm: '금속',
        type: 'stock',
        DailyPrice: 45000,
        clpr: 43000,
        fltRt: 0.02,
        Field: 2,
    },
    {
        id: 5,
        StockName: 'E통신',
        itmsNm: '통신',
        type: 'stock',
        DailyPrice: 70000,
        clpr: 68000,
        fltRt: 0.06,
        Field: 5,
    },
    {
        id: 6,
        StockName: 'F제약',
        itmsNm: '제약',
        type: 'stock',
        DailyPrice: 90000,
        clpr: 87000,
        fltRt: 0.01,
        Field: 3,
    },
    {
        id: 7,
        StockName: 'G소프트웨어',
        itmsNm: 'IT',
        type: 'stock',
        DailyPrice: 150000,
        clpr: 148000,
        fltRt: 0.07,
        Field: 4,
    },
    {
        id: 8,
        StockName: 'H농업',
        itmsNm: '농업',
        type: 'stock',
        DailyPrice: 32000,
        clpr: 31000,
        fltRt: 0.05,
        Field: 3,
    },
    {
        id: 9,
        StockName: 'I에너지',
        itmsNm: '에너지',
        type: 'stock',
        DailyPrice: 47000,
        clpr: 46000,
        fltRt: 0.02,
        Field: 2,
    },
    {
        id: 10,
        StockName: 'J금융',
        itmsNm: '금융',
        type: 'stock',
        DailyPrice: 72000,
        clpr: 70000,
        fltRt: 0.04,
        Field: 4,
    },
    {
        id: 11,
        StockName: 'K비행기',
        itmsNm: '항공',
        type: 'stock',
        DailyPrice: 200000,
        clpr: 195000,
        fltRt: 0.03,
        Field: 5,
    },
    {
        id: 12,
        StockName: 'L제조',
        itmsNm: '제조',
        type: 'stock',
        DailyPrice: 55000,
        clpr: 54000,
        fltRt: 0.06,
        Field: 3,
    },
    {
        id: 13,
        StockName: 'M소매',
        itmsNm: '소매',
        type: 'stock',
        DailyPrice: 38000,
        clpr: 37000,
        fltRt: 0.05,
        Field: 2,
    },
    {
        id: 14,
        StockName: 'N식음료',
        itmsNm: '식음료',
        type: 'stock',
        DailyPrice: 60000,
        clpr: 59000,
        fltRt: 0.02,
        Field: 3,
    },
    {
        id: 15,
        StockName: 'O건설',
        itmsNm: '건설',
        type: 'stock',
        DailyPrice: 80000,
        clpr: 78000,
        fltRt: 0.04,
        Field: 4,
    },
];
