export const dummyProducts = [
    { id: 1, name: '정기예금 A', type: 'savings' },
    { id: 2, name: '국채 B', type: 'bonds', yield: [1.2, 1.5, 1.8] },
    { id: 3, name: '펀드 C', type: 'funds', yield: [3.2, 3.5, 3.8] },
    { id: 4, name: '정기예금 D', type: 'savings' },
    { id: 5, name: '회사채 E', type: 'bonds', yield: [2.1, 2.4, 2.7] },
    { id: 6, name: '펀드 F', type: 'funds', yield: [4.0, 4.2, 4.5] },
    { id: 7, name: '정기예금 G', type: 'savings' },
    { id: 8, name: '국채 H', type: 'bonds', yield: [1.8, 2.0, 2.2] },
    { id: 9, name: '펀드 I', type: 'funds', yield: [3.0, 3.3, 3.5] },
    { id: 10, name: '회사채 J', type: 'bonds', yield: [2.5, 2.7, 3.0] },
    { id: 11, name: '정기예금 K', type: 'savings' },
    { id: 12, name: '국채 L', type: 'bonds', yield: [1.9, 2.1, 2.3] },
    { id: 13, name: '펀드 M', type: 'funds', yield: [3.5, 3.8, 4.0] },
    { id: 14, name: '정기예금 N', type: 'savings' },
    { id: 15, name: '회사채 O', type: 'bonds', yield: [2.6, 2.9, 3.1] },
    { id: 16, name: '펀드 P', type: 'funds', yield: [4.1, 4.3, 4.6] },
    { id: 17, name: '정기예금 Q', type: 'savings' },
    { id: 18, name: '국채 R', type: 'bonds', yield: [1.7, 2.2, 2.5] },
    { id: 19, name: '펀드 S', type: 'funds', yield: [3.7, 4.0, 4.2] },
    { id: 20, name: '회사채 T', type: 'bonds', yield: [2.8, 3.0, 3.3] },
    { id: 21, name: '정기예금 U', type: 'savings' },
    { id: 22, name: '국채 V', type: 'bonds', yield: [1.6, 1.9, 2.4] },
    { id: 23, name: '펀드 W', type: 'funds', yield: [3.8, 4.1, 4.4] },
    { id: 24, name: '정기예금 X', type: 'savings' },
    { id: 25, name: '회사채 Y', type: 'bonds', yield: [2.3, 2.5, 2.8] },
    { id: 26, name: '펀드 Z', type: 'funds', yield: [4.2, 4.4, 4.7] },
    { id: 27, name: '정기예금 AA', type: 'savings' },
    { id: 28, name: '국채 AB', type: 'bonds', yield: [1.4, 1.7, 1.9] },
    { id: 29, name: '펀드 AC', type: 'funds', yield: [3.4, 3.6, 3.9] },
    { id: 30, name: '회사채 AD', type: 'bonds', yield: [2.0, 2.2, 2.5] },
];
